// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4uqknI6XPmZlN02PXb0n9ZTHqju8-xPM',
    appId: '1:909427331813:web:7adfae2be8f8a18a05fa0c',
    messagingSenderId: '909427331813',
    projectId: 'zylutest',
    authDomain: 'zylutest.firebaseapp.com',
    storageBucket: 'zylutest.appspot.com',
    measurementId: 'G-HYWX847BC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4b3hfVW_lMyG2GGcWh2hwC6QosPY8b2I',
    appId: '1:909427331813:android:c147eba0e51238cf05fa0c',
    messagingSenderId: '909427331813',
    projectId: 'zylutest',
    storageBucket: 'zylutest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYoQoxOB9URhNZyqlTJw7KBmPbWKwrs00',
    appId: '1:909427331813:ios:31e1a796bed5c19a05fa0c',
    messagingSenderId: '909427331813',
    projectId: 'zylutest',
    storageBucket: 'zylutest.appspot.com',
    iosBundleId: 'com.example.zyluTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYoQoxOB9URhNZyqlTJw7KBmPbWKwrs00',
    appId: '1:909427331813:ios:56c18f40e432064f05fa0c',
    messagingSenderId: '909427331813',
    projectId: 'zylutest',
    storageBucket: 'zylutest.appspot.com',
    iosBundleId: 'com.example.zyluTest.RunnerTests',
  );
}
